---
abstract: "Maintain session IDs using mobile phone's unique id"
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Session-State-MobileAttributeID
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::StickyQuery::DoCoMoGUID: 0.01
  HTTP::MobileAttribute: 0.23
  HTTP::Session: 0.43
  Net::CIDR::MobileJP: 0.21
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.39
